name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if different

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build and deploy to GitHub Pages
        uses: actions/deploy-pages@v4
