name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if it's different

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Clone the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Prepare static files
      - name: Prepare static files
        run: |
          mkdir -p public
          cp index.html public/

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          folder: public
